name: movison
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  country_picker: ^2.0.18
  firebase_core: ^3.3.0
  fluttertoast: ^8.2.6
  firebase_auth: ^5.1.3
  cloud_firestore: ^5.2.0
  firebase_storage: ^12.1.2
  shared_preferences: ^2.0.15
  provider: ^6.0.4
  google_fonts: ^6.2.1
  pinput: ^5.0.0
  dotted_border:
  intl: ^0.19.0
  image_picker: ^1.1.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  badges: ^3.1.2 
  dialog_flowtter:
  carousel_slider: ^4.2.1
  file_picker:
  flutter_plugin_android_lifecycle: ^2.0.20
  firebase_app_check: ^0.3.0+4
  razorpay_flutter: ^1.3.7
  flutter_launcher_icons: ^0.13.1
  permission_handler: ^11.3.1
  connectivity_plus: ^6.0.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.2.0
android: true
ios: true



flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/1234.png"


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/icons/categories/
    - assets/raw/
    - assets/AuthImages/
    - assets/fonts/muli/
fonts:
  - family: PatrickHand
    fonts:
      - asset: assets/fonts/PatrickHand-Regular.ttf
  - family: SourceSans3
    fonts:
      - asset: fonts/SourceSans3-VariableFont_wght.ttf
  - family: Muli
    fonts:
      - asset: assets/fonts/muli/Muli.ttf
      - asset: assets/fonts/muli/Muli-Bold.ttf
        weight: 700
      - asset: assets/fonts/muli/Muli-Light.ttf
        weight: 300
      - family: 's'
        fonts:
          - asset: fonts/Roboto-Regular.ttf

