// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRHO-2b2ysTK0RPokXclepUhXZTB41SnM',
    appId: '1:1083683176319:web:a386e2d9bff03f3652244a',
    messagingSenderId: '1083683176319',
    projectId: 'movison',
    authDomain: 'movison.firebaseapp.com',
    storageBucket: 'movison.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4NMyJx4D7SUvx6FStoKhGK0BB7R2Ipu8',
    appId: '1:1083683176319:android:f6d52f5cbbae9d8552244a',
    messagingSenderId: '1083683176319',
    projectId: 'movison',
    storageBucket: 'movison.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbg1jc3oDq9-PZGSXOyKyiM7KC9fGqh_s',
    appId: '1:1083683176319:ios:9433fafc56b02b9152244a',
    messagingSenderId: '1083683176319',
    projectId: 'movison',
    storageBucket: 'movison.appspot.com',
    iosBundleId: 'com.example.movison',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbg1jc3oDq9-PZGSXOyKyiM7KC9fGqh_s',
    appId: '1:1083683176319:ios:9433fafc56b02b9152244a',
    messagingSenderId: '1083683176319',
    projectId: 'movison',
    storageBucket: 'movison.appspot.com',
    iosBundleId: 'com.example.movison',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRHO-2b2ysTK0RPokXclepUhXZTB41SnM',
    appId: '1:1083683176319:web:261148f40f5a7ba952244a',
    messagingSenderId: '1083683176319',
    projectId: 'movison',
    authDomain: 'movison.firebaseapp.com',
    storageBucket: 'movison.appspot.com',
  );
}
